CREATE TABLESPACE Cisum
DATAFILE 'C:/bizwork/oracle_data/Cisum.dbf'
SIZE 1M AUTOEXTEND ON NEXT 500K;

CREATE USER cisum  IDENTIFIED BY cisum
DEFAULT TABLESPACE Cisum;

GRANT CONNECT TO cisum;

GRANT DBA TO cisum;